- type: entity
  parent:
    - BaseMob
    - MobAtmosExposed
    - MobCombat
    - MobBloodstream
    - MobFlammable
    - CMEntityBase
  id: MobXenoBase
  abstract: true
  components:
    - type: Xeno
    - type: XenoEvolutions
    - type: XenoPlasma
    - type: NightVision
    - type: MovementIgnoreGravity
    - type: GravityMovementSlow
      slowPercentage: 0.65
    - type: XenoTier
    - type: XenoRest
    - type: Actions
    - type: UserInterface
      interfaces:
        enum.XenoEvolutionUiKey.Key:
          type: XenoEvolutionBoundUserInterface
    - type: ShowXenoAgeIcons
      jobId: JobKseno
    - type: Insulated
    - type: CombatMode
      combatToggleAction: ActionXenoCombatModeToggle
    - type: InputMover
    - type: MobMover
    - type: Reactive
      groups:
        Flammable: [ Touch ]
        Extinguish: [ Touch ]
    - type: NpcFactionMember
      factions:
      - Xeno
    - type: Hands
    - type: Body
    - type: Climbing
    - type: Flashable
    - type: NameIdentifier
      group: GenericNumber
    - type: MobState
      allowedStates:
      - Alive
      - Critical 
      - Dead
    - type: Puller
      needsHands: false
      sprintModifier: 0.75 # Default 0.95
      walkModifier: 0.75
    - type: TypingIndicator
      proto: alien
    - type: Temperature
      heatDamageThreshold: 360
      coldDamageThreshold: -150
      currentTemperature: 310.15
    - type: Eye
    - type: Sprite
      drawdepth: Mobs
      sprite: _CM/Mobs/Xenos/queen.rsi
      layers:
      - map: [ "enum.XenoVisualLayers.Base" ]
        state: running
    - type: MobThresholds
      thresholds:
        0: Alive
        200: Critical
        300: Dead
      stateAlertDict:
        Alive: XenoHealth
        Critical: XenoCrit
        Dead: XenoDead
    - type: Damageable
      damageContainer: Biological
      damageModifierSet: Xeno
    - type: MovementSpeedModifier
      baseWalkSpeed: 5
      baseSprintSpeed: 9
    - type: MeleeWeapon
      altDisarm: false
      hidden: true
      angle: 30
      soundHit:
        collection: AlienClaw
      damage:
        groups:
          Brute: 25
    - type: Fixtures
      fixtures:
        fix1:
          shape:
            !type:PhysShapeCircle
            radius: 0.45
          density: 550
          mask:
          - MobMask
          layer:
          - MobLayer
    - type: Tag
      tags:
      - CannotSuicide
      - DoorBumpOpener
      - FootstepSound
      - Xeno
    - type: NoSlip
    - type: Perishable # Ummmm the acid kills a lot of the bacteria or something
      molsPerSecondPerUnitMass: 0.0005
    - type: Speech
      speechVerb: LargeMob
      speechSounds: Xeno
    - type: Vocal
      sounds:
        Male: Xeno
        Female: Xeno
        Unsexed: Xeno
    - type: StatusEffects
      allowed:
      - SlowedDown
      - Stutter
      - Electrocution
      - ForcedSleep
    - type: StandingState
    - type: Butcherable
      butcheringType: Knife
      spawned:
      - id: FoodMeatXeno
        amount: 5
    - type: IntrinsicRadioReceiver
    - type: IntrinsicRadioTransmitter
      channels:
      - Hivemind
    - type: ActiveRadio
      channels:
      - Hivemind
    - type: Prying
      speedModifier: 2.75
      pryPowered: true
      force: true
    - type: Bloodstream
      bloodlossThreshold: 0
      bloodRefreshAmount: 150
      bloodReagent: FluorosulfuricAcid
    - type: LizardAccent
    - type: FlashImmunity
    - type: Destructible
      thresholds:
      - trigger:
          !type:DamageTypeTrigger
          damageType: Blunt
          damage: 400
        behaviors:
        - !type:GibBehavior { }
    - type: RadiationReceiver
    - type: MobStateActions
      actions:
        Critical:
        - ActionCritSuccumb
        - ActionCritFakeDeath
        - ActionCritLastWords
    - type: Deathgasp
    - type: HealthExaminable
      examinableTypes:
      - Blunt
      - Slash
      - Piercing
      - Heat
      - Shock
    - type: DamageOnHighSpeedImpact
      damage:
        types:
          Blunt: 5
      soundHit:
        path: /Audio/Effects/hit_kick.ogg
    - type: Pullable
    - type: LightningTarget
      priority: 2
      lightningExplode: false
    - type: MiddleMouseShootKey
    - type: FootstepModifier
      footstepSoundCollection:
        collection: XenoFootstepMedium

- type: entity
  id: ActionXenoAcid
  name: Corrosive Acid
  components:
  - type: EntityTargetAction
    useDelay: 60
    itemIconStyle: NoItem
    icon:
      sprite: Actions/xeno.rsi
      state: acid_spit
    event: !type:XenoCorrosiveAcidEvent

- type: entity
  id: XenoAcid
  name: corrosive acid
  parent: CMEntityBase
  components:
  - type: Transform
    anchored: true
  - type: Sprite
    layers:
    - sprite: _CM/Effects/xeno_acid.rsi
      state: acid_normal
    drawdepth: Effects

- type: entity
  abstract: true
  parent: MobXenoBase
  id: MobXenoBaseT0
  components:
    - type: XenoTier
      tier: 0
    - type: Butcherable
      butcheringType: Knife
      spawned:
      - id: FoodMeatXeno
        amount: 2
    - type: MovementSpeedModifier
      baseWalkSpeed: 3
      baseSprintSpeed: 6
    - type: FootstepModifier
      footstepSoundCollection:
        collection: BarestepHard

- type: entity
  abstract: true
  parent: MobXenoBase
  id: MobXenoBaseT1
  components:
    - type: XenoTier
      tier: 1
    - type: Butcherable
      butcheringType: Knife
      spawned:
      - id: FoodMeatXeno
        amount: 4
      - id: ResearchMaterial
        amount: 1
    - type: MovementSpeedModifier
      baseWalkSpeed: 3
      baseSprintSpeed: 6
    - type: Puller
      needsHands: false
      sprintModifier: 0.75 # Default 0.95
      walkModifier: 0.75
    - type: XenoPullerRules
      enabled: true
      isCheckXeno: true
      blacklist:
      - C4 # grenades
      - SeismicCharge
      - ExGrenade
      - GrenadeFlashBang
      - TearGasGrenade
      - GrenadeDummy
      - GrenadeStinger
      - GrenadeIncendiary
      - GrenadeShrapnel
      - ClusterGrenade
      - EmpGranade
      - ArtyGrenade # CM14 CAS crenade
      - MobRavagerXeno # XENOS Ravager and king are not pullable
      - MobKingXeno # XENOS Ravager and king are not pullable
- type: entity
  abstract: true
  parent: MobXenoBase
  id: MobXenoBaseT2
  components:
    - type: XenoTier
      tier: 2
    - type: Butcherable
      butcheringType: Knife
      spawned:
      - id: FoodMeatXeno
        amount: 8
      - id: ResearchMaterial3000
        amount: 1
    - type: MovementSpeedModifier
      baseWalkSpeed: 2.5
      baseSprintSpeed: 5
    - type: Puller
      needsHands: false
      sprintModifier: 0.75 # Default 0.95
      walkModifier: 0.75
    - type: XenoPullerRules
      enabled: true
      isCheckXeno: true
      blacklist:
      - C4 # grenades
      - SeismicCharge
      - ExGrenade
      - GrenadeFlashBang
      - TearGasGrenade
      - GrenadeDummy
      - GrenadeStinger
      - GrenadeIncendiary
      - GrenadeShrapnel
      - ClusterGrenade
      - EmpGranade
      - ArtyGrenade # CM14 CAS crenade
      - MobRavagerXeno # XENOS Ravager and king are not pullable
      - MobKingXeno # XENOS Ravager and king are not pullable


- type: entity
  abstract: true
  parent: MobXenoBase
  id: MobXenoBaseT3
  components:
    - type: XenoTier
      tier: 3
    - type: Butcherable
      butcheringType: Knife
      spawned:
      - id: FoodMeatXeno
        amount: 12
      - id: ResearchMaterial5000
        amount: 1
    - type: MovementSpeedModifier
      baseWalkSpeed: 2.5
      baseSprintSpeed: 5
    - type: Puller
      needsHands: false
      sprintModifier: 0.75 # Default 0.95
      walkModifier: 0.75
    - type: XenoPullerRules
      enabled: true
      isCheckXeno: true
      blacklist:
      - C4 # grenades
      - SeismicCharge
      - ExGrenade
      - GrenadeFlashBang
      - TearGasGrenade
      - GrenadeDummy
      - GrenadeStinger
      - GrenadeIncendiary
      - GrenadeShrapnel
      - ClusterGrenade
      - EmpGranade
      - ArtyGrenade # CM14 CAS crenade
      - MobRavagerXeno # XENOS Ravager and king are not pullable
      - MobKingXeno # XENOS Ravager and king are not pullable

- type: entity
  abstract: true
  parent: MobXenoBase
  id: MobXenoBaseT4
  components:
    - type: XenoTier
      tier: 4
    - type: Butcherable
      butcheringType: Knife
      spawned:
      - id: FoodMeatXeno
        amount: 20
      - id: ResearchMaterial10000
        amount: 1
    - type: MovementSpeedModifier
      baseWalkSpeed: 2.5
      baseSprintSpeed: 5
    - type: FootstepModifier
      footstepSoundCollection:
        collection: XenoFootstepLarge
    - type: Puller
      needsHands: false
      sprintModifier: 0.75 # Default 0.95
      walkModifier: 0.75
    - type: XenoPullerRules
      enabled: true
      isCheckXeno: true
      blacklist:
      - C4 # grenades
      - SeismicCharge
      - ExGrenade
      - GrenadeFlashBang
      - TearGasGrenade
      - GrenadeDummy
      - GrenadeStinger
      - GrenadeIncendiary
      - GrenadeShrapnel
      - ClusterGrenade
      - EmpGranade
      - ArtyGrenade # CM14 CAS crenade
      - MobRavagerXeno # XENOS Ravager and king are not pullable
      - MobKingXeno # XENOS Ravager and king are not pullable

- type: entity
  abstract: true
  parent: MobXenoBase
  id: MobXenoBaseT5
  components:
    - type: XenoTier
      tier: 5
    - type: Butcherable
      butcheringType: Knife
      spawned:
      - id: FoodMeatXeno
        amount: 20
      - id: ResearchMaterial10000
        amount: 2
    - type: MovementSpeedModifier
      baseWalkSpeed: 3
      baseSprintSpeed: 6
    - type: FootstepModifier
      footstepSoundCollection:
        collection: XenoFootstepLarge
    - type: Puller
      needsHands: false
      sprintModifier: 0.75 # Default 0.95
      walkModifier: 0.75
    - type: XenoPullerRules
      enabled: true
      isCheckXeno: true
      blacklist:
      - C4 # grenades
      - SeismicCharge
      - ExGrenade
      - GrenadeFlashBang
      - TearGasGrenade
      - GrenadeDummy
      - GrenadeStinger
      - GrenadeIncendiary
      - GrenadeShrapnel
      - ClusterGrenade
      - EmpGranade
      - ArtyGrenade # CM14 CAS crenade
      - MobRavagerXeno # XENOS Ravager and king are not pullable
      - MobKingXeno # XENOS Ravager and king are not pullable

- type: entity
  id: MobXenoPassiveEvades
  abstract: true
  components:
  - type: XenoEvades
    missChance: 0.10
    popupIfHit: false
